// packages/angular/src/lib/rewriter.component.ts
import { isAbortError } from '@desource/browser-ai';
import { ChangeDetectionStrategy, Component, DestroyRef, computed, input, model, output } from '@angular/core';
import {
  createAngularRewriterWorkflow,
  type RewriterResult,
  type RewriterRunOptions,
  type TextToolConfiguration
} from './workflows';
import { errorText } from './component-utils';
import { BrowserAiTextToolComponent } from './text-tool.component';
import { BrowserAiMarkdownRendererComponent } from './markdown-renderer.component';

@Component({
  selector: 'browser-ai-rewriter',
  standalone: true,
  imports: [BrowserAiTextToolComponent, BrowserAiMarkdownRendererComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <browser-ai-text-tool
      #editor
      kind="rewriter"
      title="Rewriter"
      action="Rewrite"
      placeholder="Paste text to rewrite…"
      [(value)]="value"
      [result]="resultText() || 'Rewritten text will appear here.'"
      [outputText]="resultText()"
      [availability]="api.current().availability"
      [processing]="api.current().processing"
      [downloadProgress]="api.current().downloadProgress"
      [inputUsage]="api.current().inputUsage"
      [inputQuota]="api.current().inputQuota"
      [progressState]="api.current().progressState"
      [createOptions]="this.options()"
      [runOptions]="runOptions()"
      [onCheckAvailability]="autoInit() ? checkAvailability : undefined"
      [onInterrupt]="api.interrupt"
      [error]="error()"
      [disabled]="disabled()"
      (configuredRun)="execute($event.input, $event.configuration)"
      [customOutput]="true"
    >
      <div browserAiOutput>
        @if (editor.configuration().createOptions['format'] === 'plain-text') {
          <pre>{{ resultText() || 'Rewritten text will appear here.' }}</pre>
        } @else {
          <browser-ai-markdown [content]="resultText() || 'Rewritten text will appear here.'" />
        }
      </div>
    </browser-ai-text-tool>
  `
})
export class BrowserAiRewriterComponent {
  readonly value = model('');
  readonly options = input<Omit<RewriterCreateOptions, 'monitor' | 'signal'>>({});
  readonly runOptions = input<RewriterRunOptions>({});
  readonly autoInit = input(true);
  readonly disabled = input(false);
  readonly result = output<RewriterResult>();
  readonly progress = output<Parameters<NonNullable<RewriterRunOptions['onProgress']>>[0]>();
  readonly requestError = output<unknown>();
  readonly error = model('');
  readonly api;
  readonly resultText = computed(() => this.api.current().output);
  readonly checkAvailability = (options: object) => this.api.requestAvailability(options as RewriterCreateCoreOptions);
  constructor(destroyRef: DestroyRef) {
    this.api = createAngularRewriterWorkflow(destroyRef);
  }
  async execute(
    value: string,
    configuration: TextToolConfiguration = {
      createOptions: { ...this.options() },
      runOptions: { ...this.runOptions() }
    }
  ) {
    try {
      this.error.set('');
      const options = {
        ...configuration.runOptions,
        createOptions: configuration.createOptions,
        onProgress: (progress: Parameters<NonNullable<RewriterRunOptions['onProgress']>>[0]) => {
          this.runOptions().onProgress?.(progress);
          this.progress.emit(progress);
        }
      } as RewriterRunOptions;
      await this.api.rewriteStreamingToText(value, options);
      const result = this.api.state.getSnapshot().lastResult;
      if (result) this.result.emit(result);
    } catch (error) {
      if (isAbortError(error)) return;
      this.error.set(errorText(error, 'Browser AI request failed.'));
      this.requestError.emit(error);
    }
  }
}

// packages/browser-ai-react/src/components/Rewriter.tsx
import { isAbortError } from '@desource/browser-ai';
import { useState } from 'react';
import { errorText } from '../component-utils.js';
import { useRewriterWorkflow, type RewriterResult, type RewriterRunOptions } from '../workflows.js';
import { MarkdownRenderer } from './MarkdownRenderer.js';
import { TextTool } from './TextTool.js';

export interface RewriterProps {
  value?: string;
  onValueChange?(value: string): void;
  createOptions?: Omit<RewriterCreateOptions, 'monitor' | 'signal'>;
  runOptions?: RewriterRunOptions;
  autoInit?: boolean;
  disabled?: boolean;
  onResult?(result: RewriterResult): void;
  onProgress?: RewriterRunOptions['onProgress'];
  onError?(error: unknown): void;
}

export function Rewriter({
  value,
  onValueChange,
  createOptions = {},
  runOptions = {},
  autoInit = true,
  disabled = false,
  onResult,
  onProgress,
  onError
}: RewriterProps) {
  const api = useRewriterWorkflow();
  const [error, setError] = useState('');
  const output = api.output;
  return (
    <TextTool
      kind="rewriter"
      title="Rewriter"
      action="Rewrite"
      placeholder="Paste text to rewrite…"
      value={value}
      output={output || 'Rewritten text will appear here.'}
      outputText={output}
      renderOutput={(configuration) =>
        configuration.createOptions.format === 'plain-text' ? (
          output || 'Rewritten text will appear here.'
        ) : (
          <MarkdownRenderer content={output || 'Rewritten text will appear here.'} />
        )
      }
      availability={api.availability}
      processing={api.processing}
      downloadProgress={api.downloadProgress}
      inputUsage={api.inputUsage}
      inputQuota={api.inputQuota}
      progressState={api.progressState}
      createOptions={createOptions}
      runOptions={runOptions}
      onCheckAvailability={autoInit ? api.requestAvailability : undefined}
      onInterrupt={api.interrupt}
      disabled={disabled}
      error={error}
      onValueChange={onValueChange}
      onRun={async (input, configuration) => {
        try {
          setError('');
          const options = {
            ...configuration.runOptions,
            createOptions: configuration.createOptions,
            onProgress: (progress: Parameters<NonNullable<RewriterRunOptions['onProgress']>>[0]) => {
              runOptions.onProgress?.(progress);
              onProgress?.(progress);
            }
          } as RewriterRunOptions;
          await api.rewriteStreamingToText(input, options);
          const result = api.state.getSnapshot().lastResult;
          if (result) onResult?.(result);
        } catch (caught) {
          if (isAbortError(caught)) return;
          setError(errorText(caught));
          onError?.(caught);
        }
      }}
    />
  );
}
