// packages/angular/src/lib/summarizer.component.ts
import { isAbortError } from '@desource/browser-ai';
import { ChangeDetectionStrategy, Component, DestroyRef, computed, input, model, output } from '@angular/core';
import {
  createAngularSummarizerWorkflow,
  type SummarizerResult,
  type SummarizerRunOptions,
  type TextToolConfiguration
} from './workflows';
import { errorText } from './component-utils';
import { BrowserAiTextToolComponent } from './text-tool.component';
import { BrowserAiMarkdownRendererComponent } from './markdown-renderer.component';

@Component({
  selector: 'browser-ai-summarizer',
  standalone: true,
  imports: [BrowserAiTextToolComponent, BrowserAiMarkdownRendererComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <browser-ai-text-tool
      #editor
      kind="summarizer"
      title="Summarizer"
      action="Summarize"
      placeholder="Paste an article, notes, or transcript…"
      [(value)]="value"
      [result]="resultText() || 'Summary output will appear here.'"
      [outputText]="resultText()"
      [availability]="api.current().availability"
      [processing]="api.current().processing"
      [downloadProgress]="api.current().downloadProgress"
      [inputUsage]="api.current().inputUsage"
      [inputQuota]="api.current().inputQuota"
      [progressState]="api.current().progressState"
      [createOptions]="this.options()"
      [runOptions]="runOptions()"
      [onCheckAvailability]="autoInit() ? checkAvailability : undefined"
      [onInterrupt]="api.interrupt"
      [error]="error()"
      [disabled]="disabled()"
      (configuredRun)="execute($event.input, $event.configuration)"
      [customOutput]="true"
    >
      <div browserAiOutput>
        @if (editor.configuration().createOptions['format'] === 'plain-text') {
          <pre>{{ resultText() || 'Summary output will appear here.' }}</pre>
        } @else {
          <browser-ai-markdown [content]="resultText() || 'Summary output will appear here.'" />
        }
      </div>
    </browser-ai-text-tool>
  `
})
export class BrowserAiSummarizerComponent {
  readonly value = model('');
  readonly options = input<Omit<SummarizerCreateOptions, 'monitor' | 'signal'>>({});
  readonly runOptions = input<SummarizerRunOptions>({});
  readonly autoInit = input(true);
  readonly disabled = input(false);
  readonly result = output<SummarizerResult>();
  readonly progress = output<Parameters<NonNullable<SummarizerRunOptions['onProgress']>>[0]>();
  readonly requestError = output<unknown>();
  readonly error = model('');
  readonly api;
  readonly resultText = computed(() => this.api.current().output);
  readonly checkAvailability = (options: object) =>
    this.api.requestAvailability(options as SummarizerCreateCoreOptions);
  constructor(destroyRef: DestroyRef) {
    this.api = createAngularSummarizerWorkflow(destroyRef);
  }
  async execute(
    value: string,
    configuration: TextToolConfiguration = {
      createOptions: { ...this.options() },
      runOptions: { ...this.runOptions() }
    }
  ) {
    try {
      this.error.set('');
      const options = {
        ...configuration.runOptions,
        createOptions: configuration.createOptions,
        onProgress: (progress: Parameters<NonNullable<SummarizerRunOptions['onProgress']>>[0]) => {
          this.runOptions().onProgress?.(progress);
          this.progress.emit(progress);
        }
      } as SummarizerRunOptions;
      this.result.emit(await this.api.summarizeWithDetails(value, options));
    } catch (error) {
      if (isAbortError(error)) return;
      this.error.set(errorText(error, 'Browser AI request failed.'));
      this.requestError.emit(error);
    }
  }
}

// packages/browser-ai-react/src/components/Summarizer.tsx
import { isAbortError } from '@desource/browser-ai';
import { useState } from 'react';
import { errorText } from '../component-utils.js';
import { useSummarizerWorkflow, type SummarizerResult, type SummarizerRunOptions } from '../workflows.js';
import { MarkdownRenderer } from './MarkdownRenderer.js';
import { TextTool } from './TextTool.js';

export interface SummarizerProps {
  value?: string;
  onValueChange?(value: string): void;
  createOptions?: Omit<SummarizerCreateOptions, 'monitor' | 'signal'>;
  runOptions?: SummarizerRunOptions;
  autoInit?: boolean;
  disabled?: boolean;
  onResult?(result: SummarizerResult): void;
  onProgress?: SummarizerRunOptions['onProgress'];
  onError?(error: unknown): void;
}

export function Summarizer({
  value,
  onValueChange,
  createOptions = {},
  runOptions = {},
  autoInit = true,
  disabled = false,
  onResult,
  onProgress,
  onError
}: SummarizerProps) {
  const api = useSummarizerWorkflow();
  const [error, setError] = useState('');
  const output = api.output;
  return (
    <TextTool
      kind="summarizer"
      title="Summarizer"
      action="Summarize"
      placeholder="Paste an article, notes, or transcript…"
      value={value}
      output={output || 'Summary output will appear here.'}
      outputText={output}
      renderOutput={(configuration) =>
        configuration.createOptions.format === 'plain-text' ? (
          output || 'Summary output will appear here.'
        ) : (
          <MarkdownRenderer content={output || 'Summary output will appear here.'} />
        )
      }
      availability={api.availability}
      processing={api.processing}
      downloadProgress={api.downloadProgress}
      inputUsage={api.inputUsage}
      inputQuota={api.inputQuota}
      progressState={api.progressState}
      createOptions={createOptions}
      runOptions={runOptions}
      onCheckAvailability={autoInit ? api.requestAvailability : undefined}
      onInterrupt={api.interrupt}
      disabled={disabled}
      error={error}
      onValueChange={onValueChange}
      onRun={async (input, configuration) => {
        try {
          setError('');
          const options = {
            ...configuration.runOptions,
            createOptions: configuration.createOptions,
            onProgress: (progress: Parameters<NonNullable<SummarizerRunOptions['onProgress']>>[0]) => {
              runOptions.onProgress?.(progress);
              onProgress?.(progress);
            }
          } as SummarizerRunOptions;
          const result = await api.summarizeWithDetails(input, options);
          onResult?.(result);
        } catch (caught) {
          if (isAbortError(caught)) return;
          setError(errorText(caught));
          onError?.(caught);
        }
      }}
    />
  );
}
