// packages/angular/src/lib/translator.component.ts
import { isAbortError } from '@desource/browser-ai';
import { ChangeDetectionStrategy, Component, DestroyRef, computed, input, model, output } from '@angular/core';
import {
  createAngularTranslatorWorkflow,
  type TranslatorResult,
  type TranslatorRunOptions,
  type TextToolConfiguration
} from './workflows';
import { errorText } from './component-utils';
import { BrowserAiTextToolComponent } from './text-tool.component';

@Component({
  selector: 'browser-ai-translator',
  standalone: true,
  imports: [BrowserAiTextToolComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <browser-ai-text-tool
      #editor
      kind="translator"
      [autoRun]="autoTranslate()"
      [autoRunDelay]="debounceMs()"
      [onPrepare]="prepare"
      title="Translator"
      action="Translate"
      placeholder="Paste text to translate locally…"
      [(value)]="value"
      [result]="resultText() || 'Translation will appear here.'"
      [outputText]="resultText()"
      [availability]="api.current().availability"
      [processing]="api.current().processing"
      [downloadProgress]="api.current().downloadProgress"
      [inputUsage]="api.current().inputUsage"
      [inputQuota]="api.current().inputQuota"
      [progressState]="api.current().progressState"
      [createOptions]="this.createOptions()"
      [runOptions]="runOptions()"
      [onCheckAvailability]="autoInit() ? checkAvailability : undefined"
      [onInterrupt]="api.interrupt"
      [error]="error()"
      [disabled]="disabled()"
      (configuredRun)="execute($event.input, $event.configuration)"
    >
    </browser-ai-text-tool>
  `
})
export class BrowserAiTranslatorComponent {
  readonly value = model('');
  readonly options = input<Partial<Omit<TranslatorCreateOptions, 'monitor' | 'signal'>>>({});
  readonly runOptions = input<TranslatorRunOptions>({});
  readonly autoInit = input(true);
  readonly autoTranslate = input(true);
  readonly debounceMs = input(650);
  readonly disabled = input(false);
  readonly sourceLanguage = input('en');
  readonly targetLanguage = input('es');
  readonly createOptions = computed(() => ({
    sourceLanguage: this.sourceLanguage(),
    targetLanguage: this.targetLanguage(),
    ...this.options()
  }));
  readonly result = output<TranslatorResult>();
  readonly progress = output<Parameters<NonNullable<TranslatorRunOptions['onProgress']>>[0]>();
  readonly requestError = output<unknown>();
  readonly error = model('');
  readonly api;
  readonly resultText = computed(() => this.api.current().output);
  readonly prepare = (configuration: TextToolConfiguration) =>
    this.api.create(configuration.createOptions as unknown as TranslatorCreateCoreOptions);
  readonly checkAvailability = (options: object) =>
    this.api.requestAvailability(options as TranslatorCreateCoreOptions);
  constructor(destroyRef: DestroyRef) {
    this.api = createAngularTranslatorWorkflow(
      { sourceLanguage: this.sourceLanguage(), targetLanguage: this.targetLanguage(), ...this.options() },
      destroyRef
    );
  }
  async execute(
    value: string,
    configuration: TextToolConfiguration = {
      createOptions: { ...this.createOptions() },
      runOptions: { ...this.runOptions() }
    }
  ) {
    try {
      this.error.set('');
      const options = {
        ...configuration.runOptions,
        createOptions: configuration.createOptions,
        onProgress: (progress: Parameters<NonNullable<TranslatorRunOptions['onProgress']>>[0]) => {
          this.runOptions().onProgress?.(progress);
          this.progress.emit(progress);
        }
      } as TranslatorRunOptions;
      await this.api.translateStreamingToText(value, options);
      const result = this.api.state.getSnapshot().lastResult;
      if (result) this.result.emit(result);
    } catch (error) {
      if (isAbortError(error)) return;
      this.error.set(errorText(error, 'Browser AI request failed.'));
      this.requestError.emit(error);
    }
  }
}

// packages/browser-ai-react/src/components/Translator.tsx
import { isAbortError } from '@desource/browser-ai';
import { useCallback, useState } from 'react';
import { errorText } from '../component-utils.js';
import { useTranslatorWorkflow, type TranslatorResult, type TranslatorRunOptions } from '../workflows.js';

import { TextTool } from './TextTool.js';

export interface TranslatorProps {
  value?: string;
  onValueChange?(value: string): void;
  createOptions?: Partial<Omit<TranslatorCreateOptions, 'monitor' | 'signal'>>;
  runOptions?: TranslatorRunOptions;
  autoInit?: boolean;
  autoTranslate?: boolean;
  debounceMs?: number;
  disabled?: boolean;
  sourceLanguage?: string;
  targetLanguage?: string;
  onResult?(result: TranslatorResult): void;
  onProgress?: TranslatorRunOptions['onProgress'];
  onError?(error: unknown): void;
}

export function Translator({
  value,
  onValueChange,
  createOptions = {},
  runOptions = {},
  sourceLanguage = 'en',
  targetLanguage = 'es',
  autoInit = true,
  autoTranslate = true,
  debounceMs = 650,
  disabled = false,
  onResult,
  onProgress,
  onError
}: TranslatorProps) {
  const api = useTranslatorWorkflow({ sourceLanguage, targetLanguage, ...createOptions });
  const checkAvailability = api.requestAvailability;
  const requestAvailability = useCallback(
    (options: object) => checkAvailability(options as TranslatorCreateCoreOptions),
    [checkAvailability]
  );
  const [error, setError] = useState('');
  const output = api.output;
  return (
    <TextTool
      kind="translator"
      autoRun={autoTranslate}
      autoRunDelay={debounceMs}
      onPrepare={(configuration) => api.create(configuration.createOptions as unknown as TranslatorCreateCoreOptions)}
      title="Translator"
      action="Translate"
      placeholder="Paste text to translate locally…"
      value={value}
      output={output || 'Translation will appear here.'}
      outputText={output}
      availability={api.availability}
      processing={api.processing}
      downloadProgress={api.downloadProgress}
      inputUsage={api.inputUsage}
      inputQuota={api.inputQuota}
      progressState={api.progressState}
      createOptions={{ sourceLanguage, targetLanguage, ...createOptions }}
      runOptions={runOptions}
      onCheckAvailability={autoInit ? requestAvailability : undefined}
      onInterrupt={api.interrupt}
      disabled={disabled}
      error={error}
      onValueChange={onValueChange}
      onRun={async (input, configuration) => {
        try {
          setError('');
          const options = {
            ...configuration.runOptions,
            createOptions: configuration.createOptions,
            onProgress: (progress: Parameters<NonNullable<TranslatorRunOptions['onProgress']>>[0]) => {
              runOptions.onProgress?.(progress);
              onProgress?.(progress);
            }
          } as TranslatorRunOptions;
          await api.translateStreamingToText(input, options);
          const result = api.state.getSnapshot().lastResult;
          if (result) onResult?.(result);
        } catch (caught) {
          if (isAbortError(caught)) return;
          setError(errorText(caught));
          onError?.(caught);
        }
      }}
    />
  );
}
