// packages/angular/src/lib/markdown-renderer.component.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import MarkdownIt, { type MarkdownIt as MarkdownItInstance } from 'markdown-it';

let markdown: MarkdownItInstance | undefined;

@Component({
  selector: 'browser-ai-markdown',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<div class="browser-ai-markdown" [innerHTML]="rendered()"></div>'
})
export class BrowserAiMarkdownRendererComponent {
  readonly content = input('');
  readonly rendered = computed(() => {
    markdown ??= new MarkdownIt({ breaks: true, html: false, linkify: true });
    return markdown.render(this.content());
  });
}

// packages/react/src/components/MarkdownRenderer.tsx
import MarkdownIt from 'markdown-it';
import { useMemo } from 'react';

export interface MarkdownRendererProps {
  content: string;
}

export function MarkdownRenderer({ content }: MarkdownRendererProps) {
  const markdown = useMemo(() => new MarkdownIt({ breaks: true, html: false, linkify: true }), []);
  const rendered = useMemo(() => markdown.render(content), [content, markdown]);
  return <div className="browser-ai-markdown" dangerouslySetInnerHTML={{ __html: rendered }} />;
}
