// packages/browser-ai-react/src/components/ChatSidebar.tsx
import { useState } from 'react';
import type { ChatSidebarItem } from '../types.js';

export interface ChatSidebarProps {
  chats: ChatSidebarItem[];
  activeChatId: string | null;
  disabled?: boolean;
  onCreate?(): void;
  onSelect?(id: string): void;
  onRename?(id: string, title: string): void;
  onDelete?(id: string): void;
}

export function ChatSidebar({
  chats,
  activeChatId,
  disabled = false,
  onCreate,
  onSelect,
  onRename,
  onDelete
}: ChatSidebarProps) {
  const [editingId, setEditingId] = useState<string | null>(null);
  const [draft, setDraft] = useState('');
  const beginRename = (chat: ChatSidebarItem) => {
    setEditingId(chat.id);
    setDraft(chat.title);
  };
  const saveRename = (id: string) => {
    const title = draft.trim();
    if (!title) return;
    onRename?.(id, title);
    setEditingId(null);
    setDraft('');
  };

  return (
    <aside className="chat-sidebar" aria-label="Saved conversations">
      <button type="button" disabled={disabled} data-browser-ai-action="create" onClick={onCreate}>
        New chat
      </button>
      <div className="chat-sidebar__list">
        {chats.map((chat) => (
          <article
            className={chat.id === activeChatId ? 'chat-sidebar__item is-active' : 'chat-sidebar__item'}
            key={chat.id}
          >
            {editingId === chat.id ? (
              <form
                className="chat-sidebar__rename"
                onSubmit={(event) => {
                  event.preventDefault();
                  saveRename(chat.id);
                }}
              >
                <label htmlFor={`rename-${chat.id}`}>Conversation name</label>
                <input
                  id={`rename-${chat.id}`}
                  value={draft}
                  maxLength={80}
                  onChange={(event) => setDraft(event.currentTarget.value)}
                />
                <button type="submit" data-browser-ai-action="save-rename" disabled={disabled || !draft.trim()}>
                  Save
                </button>
                <button
                  type="button"
                  disabled={disabled}
                  data-browser-ai-action="cancel-rename"
                  onClick={() => setEditingId(null)}
                >
                  Cancel
                </button>
              </form>
            ) : (
              <>
                <button
                  type="button"
                  disabled={disabled}
                  data-browser-ai-action="select"
                  onClick={() => onSelect?.(chat.id)}
                >
                  {chat.title}
                </button>
                {onRename && (
                  <button
                    type="button"
                    disabled={disabled}
                    aria-label={`Rename ${chat.title}`}
                    onClick={() => beginRename(chat)}
                  >
                    Rename
                  </button>
                )}
                {onDelete && (
                  <button
                    type="button"
                    disabled={disabled}
                    aria-label={`Delete ${chat.title}`}
                    onClick={() => onDelete(chat.id)}
                  >
                    ×
                  </button>
                )}
              </>
            )}
          </article>
        ))}
      </div>
    </aside>
  );
}

// packages/svelte/src/lib/ChatSidebar.svelte
<script lang="ts">
  import type { ChatSidebarItem } from './types.js';

  export let chats: ChatSidebarItem[] = [];
  export let activeChatId: string | null = null;
  export let disabled = false;
  export let onCreate: () => void = () => undefined;
  export let onSelect: (id: string) => void = () => undefined;
  export let onRename: (id: string, title: string) => void = () => undefined;
  export let onDelete: (id: string) => void = () => undefined;

  let editingId: string | null = null;
  let renameDraft = '';
  const beginRename = (chat: ChatSidebarItem) => {
    editingId = chat.id;
    renameDraft = chat.title;
  };
  const saveRename = (id: string) => {
    const title = renameDraft.trim();
    if (!title) return;
    onRename(id, title);
    editingId = null;
    renameDraft = '';
  };
</script>

<aside class="chat-sidebar" aria-label="Saved conversations">
  <button type="button" {disabled} data-browser-ai-action="create" on:click={onCreate}>New chat</button>
  <div class="chat-sidebar__list">
    {#each chats as chat (chat.id)}
      <article class:chat-sidebar__item={true} class:is-active={chat.id === activeChatId}>
        {#if editingId === chat.id}
          <form class="chat-sidebar__rename" on:submit|preventDefault={() => saveRename(chat.id)}>
            <label for={`rename-${chat.id}`}>Conversation name</label>
            <input id={`rename-${chat.id}`} bind:value={renameDraft} maxlength="80" />
            <button type="submit" {disabled} data-browser-ai-action="save-rename">Save</button>
            <button type="button" {disabled} data-browser-ai-action="cancel-rename" on:click={() => (editingId = null)}
              >Cancel</button
            >
          </form>
        {:else}
          <button type="button" {disabled} data-browser-ai-action="select" on:click={() => onSelect(chat.id)}
            >{chat.title}</button
          >
          <button type="button" {disabled} aria-label={`Rename ${chat.title}`} on:click={() => beginRename(chat)}
            >Rename</button
          >
          <button type="button" {disabled} aria-label={`Delete ${chat.title}`} on:click={() => onDelete(chat.id)}
            >×</button
          >
        {/if}
      </article>
    {/each}
  </div>
</aside>
