// packages/angular/src/lib/chat-sidebar.component.ts
import { ChangeDetectionStrategy, Component, input, output, signal } from '@angular/core';
import type { ChatSidebarItem } from './types';

@Component({
  selector: 'browser-ai-chat-sidebar',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <aside class="chat-sidebar" aria-label="Saved conversations">
      <button type="button" [disabled]="disabled()" data-browser-ai-action="create" (click)="create.emit()">
        New chat
      </button>
      <div class="chat-sidebar__list">
        @for (chat of chats(); track chat.id) {
          <article class="chat-sidebar__item" [class.is-active]="chat.id === activeChatId()">
            @if (editingId() === chat.id) {
              <form class="chat-sidebar__rename" (submit)="saveRename($event, chat.id)">
                <label [for]="'rename-' + chat.id">Conversation name</label>
                <input
                  [id]="'rename-' + chat.id"
                  [value]="renameDraft()"
                  maxlength="80"
                  (input)="updateRename($event)"
                />
                <button
                  type="submit"
                  [disabled]="disabled() || !renameDraft().trim()"
                  data-browser-ai-action="save-rename"
                >
                  Save
                </button>
                <button
                  type="button"
                  [disabled]="disabled()"
                  data-browser-ai-action="cancel-rename"
                  (click)="cancelRename()"
                >
                  Cancel
                </button>
              </form>
            } @else {
              <button
                type="button"
                [disabled]="disabled()"
                data-browser-ai-action="select"
                (click)="select.emit(chat.id)"
              >
                {{ chat.title }}
              </button>
              <button
                type="button"
                [disabled]="disabled()"
                [attr.aria-label]="'Rename ' + chat.title"
                (click)="beginRename(chat)"
              >
                Rename
              </button>
              <button
                type="button"
                [disabled]="disabled()"
                [attr.aria-label]="'Delete ' + chat.title"
                (click)="delete.emit(chat.id)"
              >
                ×
              </button>
            }
          </article>
        }
      </div>
    </aside>
  `
})
export class BrowserAiChatSidebarComponent {
  readonly chats = input<readonly ChatSidebarItem[]>([]);
  readonly activeChatId = input<string | null>(null);
  readonly disabled = input(false);
  readonly create = output<void>();
  readonly select = output<string>();
  readonly rename = output<{ id: string; title: string }>();
  readonly delete = output<string>();
  readonly editingId = signal<string | null>(null);
  readonly renameDraft = signal('');

  beginRename(chat: ChatSidebarItem) {
    this.editingId.set(chat.id);
    this.renameDraft.set(chat.title);
  }

  updateRename(event: Event) {
    this.renameDraft.set((event.currentTarget as HTMLInputElement).value);
  }

  cancelRename() {
    this.editingId.set(null);
    this.renameDraft.set('');
  }

  saveRename(event: Event, id: string) {
    event.preventDefault();
    const title = this.renameDraft().trim();
    if (!title) return;
    this.rename.emit({ id, title });
    this.cancelRename();
  }
}

// packages/svelte/src/lib/ChatSidebar.svelte
<script lang="ts">
  import type { ChatSidebarItem } from './types.js';

  export let chats: ChatSidebarItem[] = [];
  export let activeChatId: string | null = null;
  export let disabled = false;
  export let onCreate: () => void = () => undefined;
  export let onSelect: (id: string) => void = () => undefined;
  export let onRename: (id: string, title: string) => void = () => undefined;
  export let onDelete: (id: string) => void = () => undefined;

  let editingId: string | null = null;
  let renameDraft = '';
  const beginRename = (chat: ChatSidebarItem) => {
    editingId = chat.id;
    renameDraft = chat.title;
  };
  const saveRename = (id: string) => {
    const title = renameDraft.trim();
    if (!title) return;
    onRename(id, title);
    editingId = null;
    renameDraft = '';
  };
</script>

<aside class="chat-sidebar" aria-label="Saved conversations">
  <button type="button" {disabled} data-browser-ai-action="create" on:click={onCreate}>New chat</button>
  <div class="chat-sidebar__list">
    {#each chats as chat (chat.id)}
      <article class:chat-sidebar__item={true} class:is-active={chat.id === activeChatId}>
        {#if editingId === chat.id}
          <form class="chat-sidebar__rename" on:submit|preventDefault={() => saveRename(chat.id)}>
            <label for={`rename-${chat.id}`}>Conversation name</label>
            <input id={`rename-${chat.id}`} bind:value={renameDraft} maxlength="80" />
            <button type="submit" {disabled} data-browser-ai-action="save-rename">Save</button>
            <button type="button" {disabled} data-browser-ai-action="cancel-rename" on:click={() => (editingId = null)}
              >Cancel</button
            >
          </form>
        {:else}
          <button type="button" {disabled} data-browser-ai-action="select" on:click={() => onSelect(chat.id)}
            >{chat.title}</button
          >
          <button type="button" {disabled} aria-label={`Rename ${chat.title}`} on:click={() => beginRename(chat)}
            >Rename</button
          >
          <button type="button" {disabled} aria-label={`Delete ${chat.title}`} on:click={() => onDelete(chat.id)}
            >×</button
          >
        {/if}
      </article>
    {/each}
  </div>
</aside>
