// packages/browser-ai-react/src/components/TextTool.tsx
import { readTextSource } from '@desource/browser-ai';
import {
  createAutoRun,
  getTextToolSettings,
  parseToolSetting,
  resolveTextToolOptions,
  type TextToolKind,
  type TextToolConfiguration,
  type NormalizedProofreadCorrection
} from '@desource/browser-ai/workflows';
import { type ChangeEvent, type FormEvent, type ReactNode, useEffect, useRef, useState } from 'react';
import { errorText, TEXT_FILE_ACCEPT } from '../component-utils.js';

export type { TextToolConfiguration } from '@desource/browser-ai/workflows';
export interface TextToolProps {
  kind?: TextToolKind;
  title: string;
  action: string;
  placeholder: string;
  value?: string;
  output: ReactNode;
  outputText?: string;
  renderOutput?(configuration: TextToolConfiguration): ReactNode;
  corrections?: readonly NormalizedProofreadCorrection[];
  availability: Availability | null;
  processing: string;
  downloadProgress?: number;
  inputUsage?: number | null;
  inputQuota?: number | null;
  progressState?: { phase: string; processedChunks?: number; totalChunks?: number };
  createOptions?: object;
  runOptions?: object;
  onCheckAvailability?(options: object): Promise<Availability>;
  onInterrupt?(): void;
  autoRun?: boolean;
  autoRunDelay?: number;
  onPrepare?(configuration: TextToolConfiguration): Promise<unknown>;
  disabled?: boolean;
  error?: string;
  onValueChange?(value: string): void;
  onRun(input: string, configuration: TextToolConfiguration): Promise<void>;
}

export function TextTool({
  kind,
  title,
  action,
  placeholder,
  value = '',
  output,
  outputText = '',
  renderOutput,
  corrections = [],
  availability,
  processing,
  downloadProgress = 0,
  inputUsage,
  inputQuota,
  progressState,
  createOptions = {},
  runOptions = {},
  onCheckAvailability,
  onInterrupt,
  autoRun = false,
  autoRunDelay = 650,
  onPrepare,
  disabled = false,
  error,
  onValueChange,
  onRun
}: TextToolProps) {
  const [input, setInput] = useState(value);
  const [autoEnabled, setAutoEnabled] = useState(autoRun);
  const runner = useRef<ReturnType<typeof createAutoRun> | null>(null);
  const runCallback = useRef(onRun);
  useEffect(() => {
    runCallback.current = onRun;
  }, [onRun]);
  useEffect(() => setAutoEnabled(autoRun), [autoRun]);
  const [fileError, setFileError] = useState('');
  const [copied, setCopied] = useState(false);
  const key = JSON.stringify([createOptions, runOptions]);
  const [selection, setSelection] = useState({ key, createOptions: {}, runOptions: {} } as TextToolConfiguration & {
    key: string;
  });
  const baseline = kind
    ? resolveTextToolOptions(kind, createOptions, runOptions)
    : { createOptions: { ...createOptions }, runOptions: { ...runOptions } };
  const configuration = {
    createOptions: { ...baseline.createOptions, ...(selection.key === key ? selection.createOptions : {}) },
    runOptions: { ...baseline.runOptions, ...(selection.key === key ? selection.runOptions : {}) }
  };
  const fields = kind ? getTextToolSettings(kind) : [];
  const availabilityKey = JSON.stringify(configuration.createOptions);
  const mounted = useRef(false);
  const fileRequest = useRef(0);
  const copyRequest = useRef(0);
  const inputRef = useRef(input);
  const busy = Boolean(processing);
  const blockedRef = useRef(disabled || busy);
  useEffect(() => {
    inputRef.current = input;
  }, [input]);
  useEffect(() => {
    copyRequest.current += 1;
    setCopied(false);
  }, [outputText]);
  useEffect(() => {
    blockedRef.current = disabled || busy;
  }, [disabled, busy]);
  useEffect(() => {
    setInput(value);
    inputRef.current = value;
  }, [value]);
  useEffect(() => {
    mounted.current = true;
    return () => {
      mounted.current = false;
      fileRequest.current += 1;
    };
  }, []);
  useEffect(() => {
    let active = true;
    if (onCheckAvailability) {
      setFileError('');
      void onCheckAvailability(JSON.parse(availabilityKey)).catch((caught: unknown) => {
        if (active) setFileError(errorText(caught));
      });
    }
    return () => {
      active = false;
    };
  }, [onCheckAvailability, availabilityKey]);

  const runKey = JSON.stringify(configuration);
  useEffect(() => {
    runner.current = createAutoRun(
      (text, options) => {
        setFileError('');
        return runCallback.current(text, options);
      },
      (caught) => setFileError(errorText(caught))
    );
    return () => {
      runner.current?.dispose();
      runner.current = null;
    };
  }, []);
  useEffect(() => {
    runner.current?.update({
      input,
      configuration: JSON.parse(runKey),
      enabled: kind === 'translator' && autoEnabled,
      available: availability,
      busy,
      disabled,
      delayMs: autoRunDelay
    });
  }, [input, runKey, kind, autoEnabled, availability, busy, disabled, autoRunDelay]);
  const interrupt = () => {
    runner.current?.stop();
    onInterrupt?.();
  };
  const swap = () => {
    runner.current?.stop();
    setSelection({
      key,
      createOptions: {
        ...configuration.createOptions,
        sourceLanguage: configuration.createOptions.targetLanguage,
        targetLanguage: configuration.createOptions.sourceLanguage
      },
      runOptions: configuration.runOptions
    });
  };
  const prepare = async () => {
    try {
      setFileError('');
      await onPrepare?.(configuration);
    } catch (caught) {
      setFileError(errorText(caught));
    }
  };
  const fileChanged = async (event: ChangeEvent<HTMLInputElement>) => {
    const target = event.currentTarget;
    if (disabled || busy) return;
    const request = ++fileRequest.current;
    try {
      const blocks = await Promise.all(Array.from(target.files ?? []).map((file) => readTextSource(file)));
      if (!mounted.current || request !== fileRequest.current || blockedRef.current) return;
      const next = [inputRef.current, ...blocks].filter(Boolean).join('\n\n');
      inputRef.current = next;
      setInput(next);
      onValueChange?.(next);
      setFileError('');
    } catch (caught) {
      if (mounted.current && request === fileRequest.current) setFileError(errorText(caught, 'Could not read file.'));
    } finally {
      target.value = '';
    }
  };
  const submit = (event: FormEvent) => {
    event.preventDefault();
    if (input.trim() && !busy && !disabled)
      void runner.current?.runNow(input, configuration).catch((caught) => setFileError(errorText(caught)));
  };
  const copy = async () => {
    const request = ++copyRequest.current;
    try {
      await navigator.clipboard.writeText(outputText);
      if (mounted.current && request === copyRequest.current) {
        setCopied(true);
        setFileError('');
      }
    } catch (caught) {
      if (mounted.current && request === copyRequest.current)
        setFileError(errorText(caught, 'Could not copy the result.'));
    }
  };

  return (
    <form className="writing-tool" onSubmit={submit}>
      <div className="writing-tool__toolbar">
        <div className="writing-tool__toolbar-main">
          <strong>{title}</strong>
          <span className="writing-tool__status">{availability ?? 'checking'}</span>
        </div>
      </div>
      <div className="writing-tool__workspace">
        <section className="writing-tool__pane writing-tool__editor">
          <textarea
            value={input}
            placeholder={placeholder}
            disabled={disabled || busy}
            onChange={(event) => {
              inputRef.current = event.currentTarget.value;
              setInput(event.currentTarget.value);
              onValueChange?.(event.currentTarget.value);
            }}
          />
          <label className="writing-tool__ghost-button">
            Add text files
            <input
              hidden
              type="file"
              multiple
              accept={TEXT_FILE_ACCEPT}
              disabled={disabled || busy}
              onChange={fileChanged}
            />
          </label>
          {kind === 'translator' && (
            <div className="writing-tool__language-actions">
              <label>
                <input
                  type="checkbox"
                  checked={autoEnabled}
                  disabled={disabled || busy}
                  onChange={(event) => setAutoEnabled(event.currentTarget.checked)}
                />
                Auto translate
              </label>
              <button type="button" disabled={disabled || busy} onClick={swap}>
                Swap languages
              </button>
              {onPrepare && availability === 'downloadable' && (
                <button type="button" disabled={disabled || busy} onClick={() => void prepare()}>
                  Download pack
                </button>
              )}
            </div>
          )}
          {fields.length > 0 && (
            <details className="writing-tool__settings">
              <summary>Settings</summary>
              <div className="writing-tool__settings-grid">
                {fields.map((field) => {
                  const values = field.target === 'create' ? configuration.createOptions : configuration.runOptions;
                  const selected = values[field.key] ?? field.defaultValue;
                  const change = (raw: string | boolean) =>
                    setSelection((previous) => {
                      const own = previous.key === key ? previous : { key, createOptions: {}, runOptions: {} };
                      const group = field.target === 'create' ? 'createOptions' : 'runOptions';
                      return { ...own, [group]: { ...own[group], [field.key]: parseToolSetting(field, raw) } };
                    });
                  return (
                    <label key={`${field.target}.${field.key}`}>
                      {field.label}
                      {field.type === 'select' ? (
                        <select
                          disabled={disabled || busy}
                          value={String(selected)}
                          onChange={(event) => change(event.currentTarget.value)}
                        >
                          {field.options?.map((option) => (
                            <option key={option.value} value={option.value}>
                              {option.label}
                            </option>
                          ))}
                        </select>
                      ) : field.type === 'checkbox' ? (
                        <input
                          type="checkbox"
                          disabled={disabled || busy}
                          checked={Boolean(selected)}
                          onChange={(event) => change(event.currentTarget.checked)}
                        />
                      ) : field.type === 'textarea' ? (
                        <textarea
                          disabled={disabled || busy}
                          value={String(selected)}
                          onChange={(event) => change(event.currentTarget.value)}
                        />
                      ) : (
                        <input
                          type={field.type === 'number' ? 'number' : 'text'}
                          disabled={disabled || busy}
                          min={field.min}
                          max={field.max}
                          step={field.step}
                          value={Array.isArray(selected) ? selected.join(', ') : String(selected)}
                          onChange={(event) => change(event.currentTarget.value)}
                        />
                      )}
                    </label>
                  );
                })}
              </div>
            </details>
          )}
        </section>
        <section className="writing-tool__pane writing-tool__pane--output">
          <div className="writing-tool__output">{renderOutput ? renderOutput(configuration) : output}</div>
          {corrections.length > 0 && (
            <ul className="proofreader-tool__corrections" aria-label="Corrections">
              {corrections.map((correction, index) => (
                <li key={index}>
                  <del>{correction.original}</del> <ins>{correction.correction}</ins>
                  {correction.types.length > 0 && <span> {correction.types.join(', ')}</span>}
                  {correction.explanation && <p>{correction.explanation}</p>}
                </li>
              ))}
            </ul>
          )}
          {outputText && (
            <button type="button" onClick={() => void copy()}>
              {copied ? 'Copied' : 'Copy output'}
            </button>
          )}
        </section>
      </div>
      {(error || fileError) && (
        <p className="writing-tool__error" role="alert">
          {error || fileError}
        </p>
      )}
      <footer className="writing-tool__footer">
        <span>
          {inputUsage ?? '—'} / {inputQuota ?? '—'} tokens
        </span>
        {busy && (
          <span role="status">
            {progressState?.phase ?? processing}
            {downloadProgress > 0 && downloadProgress < 100 ? ` ${Math.round(downloadProgress)}%` : ''}
            {progressState?.totalChunks ? ` ${progressState.processedChunks ?? 0}/${progressState.totalChunks}` : ''}
          </span>
        )}
        {busy && onInterrupt && (
          <button type="button" onClick={interrupt}>
            Stop
          </button>
        )}
        <button type="submit" data-browser-ai-action="run" disabled={disabled || busy || !input.trim()}>
          {busy ? 'Working…' : availability === 'downloadable' ? `Download & ${action.toLowerCase()}` : action}
        </button>
      </footer>
    </form>
  );
}

// packages/svelte/src/lib/TextTool.svelte
<script lang="ts">
  import { onDestroy, onMount } from 'svelte';
  import { readTextSource, TEXT_FILE_ACCEPT } from '@desource/browser-ai';
  import {
    createAutoRun,
    getTextToolSettings,
    parseToolSetting,
    resolveTextToolOptions,
    type NormalizedProofreadCorrection,
    type TextToolConfiguration,
    type TextToolKind,
    type ToolSetting
  } from '@desource/browser-ai/workflows';
  import { errorMessage } from './error-message.js';

  export let title: string;
  export let action: string;
  export let placeholder: string;
  export let kind: TextToolKind | undefined = undefined;
  export let value = '';
  export let output = '';
  export let outputText: string | undefined = undefined;
  export let renderMarkdown = true;
  export let corrections: readonly NormalizedProofreadCorrection[] = [];
  export let availability: Availability | null = null;
  export let processing = '';
  export let downloadProgress = 0;
  export let inputUsage: number | null | undefined = undefined;
  export let inputQuota: number | null | undefined = undefined;
  export let progressState: { phase: string; processedChunks?: number; totalChunks?: number } | undefined = undefined;
  export let createOptions: object = {};
  export let runOptions: object = {};
  export let error = '';
  export let disabled = false;
  export let onValueChange: ((value: string) => void) | undefined = undefined;
  export let onRun: (value: string, configuration: TextToolConfiguration) => Promise<void> = async () => undefined;
  export let onCheckAvailability: ((options: object) => Promise<Availability>) | undefined = undefined;
  export let onInterrupt: (() => void) | undefined = undefined;

  export let autoRun = false;
  export let autoRunDelay = 650;
  export let onPrepare: ((configuration: TextToolConfiguration) => Promise<unknown>) | undefined = undefined;
  let autoEnabled = autoRun;
  $: autoEnabled = autoRun;
  const runner = createAutoRun(
    (input, options) => {
      localError = '';
      return onRun(input, options);
    },
    (caught) => {
      localError = errorMessage(caught, 'Could not complete the request.');
    }
  );
  let mounted = false;
  let fileRequest = 0;
  let availabilityRequest = 0;
  let runRequest = 0;
  let copyRequest = 0;
  let localError = '';
  let availabilityError = '';
  let copied = false;
  let previousOutput = '';
  let submitting = false;
  let selection: TextToolConfiguration & { key: string } = { key: '', createOptions: {}, runOptions: {} };

  $: busy = Boolean(processing) || submitting;
  $: if (disabled || busy) invalidateFiles();
  $: optionKey = JSON.stringify([kind, createOptions, runOptions]);
  $: if (selection.key !== optionKey) selection = { key: optionKey, createOptions: {}, runOptions: {} };
  $: baseline = kind
    ? resolveTextToolOptions(kind, createOptions, runOptions)
    : { createOptions: { ...createOptions }, runOptions: { ...runOptions } };
  $: configuration = {
    createOptions: { ...baseline.createOptions, ...selection.createOptions },
    runOptions: { ...baseline.runOptions, ...selection.runOptions }
  } satisfies TextToolConfiguration;
  $: if (mounted)
    runner.update({
      input: value,
      configuration,
      enabled: kind === 'translator' && autoEnabled,
      available: availability,
      busy,
      disabled,
      delayMs: autoRunDelay
    });
  $: fields = kind ? getTextToolSettings(kind) : [];
  $: availabilityKey = JSON.stringify(configuration.createOptions);
  $: if (mounted) checkAvailability(onCheckAvailability, availabilityKey);
  $: copyText = outputText ?? output;
  $: if (copyText !== previousOutput) {
    previousOutput = copyText;
    copied = false;
    copyRequest += 1;
  }

  onMount(() => {
    mounted = true;
  });
  onDestroy(() => {
    mounted = false;
    runner.dispose();
    fileRequest += 1;
    availabilityRequest += 1;
    runRequest += 1;
    copyRequest += 1;
  });

  async function checkAvailability(check: typeof onCheckAvailability, key: string) {
    const request = ++availabilityRequest;
    availabilityError = '';
    if (!check) return;
    try {
      await check(JSON.parse(key));
    } catch (caught) {
      if (mounted && request === availabilityRequest && check === onCheckAvailability && key === availabilityKey) {
        availabilityError = errorMessage(caught, 'Could not check availability.');
      }
    }
  }

  function invalidateFiles() {
    fileRequest += 1;
  }

  function settingValue(field: ToolSetting, options: TextToolConfiguration) {
    const values = field.target === 'create' ? options.createOptions : options.runOptions;
    return values[field.key] ?? field.defaultValue;
  }

  function changeSetting(field: ToolSetting, raw: string | boolean) {
    if (disabled || busy) return;
    const group = field.target === 'create' ? 'createOptions' : 'runOptions';
    selection = { ...selection, [group]: { ...selection[group], [field.key]: parseToolSetting(field, raw) } };
  }

  const filesChanged = async (event: Event) => {
    const target = event.currentTarget as HTMLInputElement;
    const request = ++fileRequest;
    try {
      if (disabled || busy) return;
      const blocks = await Promise.all(Array.from(target.files ?? []).map((file) => readTextSource(file)));
      if (!mounted || request !== fileRequest || disabled || busy) return;
      value = [value, ...blocks].filter(Boolean).join('\n\n');
      onValueChange?.(value);
      localError = '';
    } catch (caught) {
      if (mounted && request === fileRequest && !disabled && !busy)
        localError = errorMessage(caught, 'Could not read file.');
    } finally {
      target.value = '';
    }
  };

  const interrupt = () => {
    runner.stop();
    runRequest += 1;
    submitting = false;
    onInterrupt?.();
  };

  const submit = async () => {
    const input = value.trim();
    if (!input || busy || disabled) return;
    const request = ++runRequest;
    submitting = true;
    localError = '';
    try {
      await runner.runNow(input, configuration);
    } catch (caught) {
      if (mounted && request === runRequest) localError = errorMessage(caught, 'Could not complete the request.');
    } finally {
      if (mounted && request === runRequest) submitting = false;
    }
  };

  const swap = () => {
    runner.stop();
    selection = {
      key: optionKey,
      createOptions: {
        ...configuration.createOptions,
        sourceLanguage: configuration.createOptions.targetLanguage,
        targetLanguage: configuration.createOptions.sourceLanguage
      },
      runOptions: configuration.runOptions
    };
  };
  const prepare = async () => {
    try {
      localError = '';
      await onPrepare?.(configuration);
    } catch (caught) {
      localError = errorMessage(caught, 'Could not prepare the language pair.');
    }
  };

  const copy = async () => {
    if (disabled || busy || !copyText) return;
    const request = ++copyRequest;
    const text = copyText;
    try {
      await navigator.clipboard.writeText(text);
      if (mounted && request === copyRequest && copyText === text) copied = true;
    } catch (caught) {
      if (mounted && request === copyRequest && copyText === text)
        localError = errorMessage(caught, 'Could not copy the result.');
    }
  };
</script>

<form class="writing-tool" on:submit|preventDefault={submit}>
  <div class="writing-tool__toolbar">
    <div class="writing-tool__toolbar-main">
      <strong>{title}</strong><span class="writing-tool__status">{availability ?? 'checking'}</span>
    </div>
  </div>
  <div class="writing-tool__workspace">
    <section class="writing-tool__pane writing-tool__editor">
      <textarea bind:value {placeholder} disabled={disabled || busy} on:input={() => onValueChange?.(value)}></textarea>
      <label class="writing-tool__ghost-button">
        Add text files<input
          hidden
          type="file"
          multiple
          accept={TEXT_FILE_ACCEPT}
          disabled={disabled || busy}
          on:change={filesChanged}
        />
      </label>
      {#if kind === 'translator'}<div class="writing-tool__language-actions">
          <label><input type="checkbox" bind:checked={autoEnabled} disabled={disabled || busy} />Auto translate</label>
          <button type="button" disabled={disabled || busy} on:click={swap}>Swap languages</button>
          {#if onPrepare && availability === 'downloadable'}<button
              type="button"
              disabled={disabled || busy}
              on:click={prepare}>Download pack</button
            >{/if}
        </div>{/if}
      {#if fields.length}
        <details class="writing-tool__settings">
          <summary>Settings</summary>
          <div class="writing-tool__settings-grid">
            {#each fields as field (`${field.target}.${field.key}`)}
              {@const selected = settingValue(field, configuration)}
              <label>
                {field.label}
                {#if field.type === 'select'}
                  <select
                    disabled={disabled || busy}
                    value={String(selected)}
                    on:change={(event) => changeSetting(field, event.currentTarget.value)}
                  >
                    {#each field.options ?? [] as option (option.value)}<option value={option.value}
                        >{option.label}</option
                      >{/each}
                  </select>
                {:else if field.type === 'checkbox'}
                  <input
                    type="checkbox"
                    disabled={disabled || busy}
                    checked={Boolean(selected)}
                    on:change={(event) => changeSetting(field, event.currentTarget.checked)}
                  />
                {:else if field.type === 'textarea'}
                  <textarea
                    disabled={disabled || busy}
                    value={String(selected)}
                    on:input={(event) => changeSetting(field, event.currentTarget.value)}></textarea>
                {:else}
                  <input
                    type={field.type === 'number' ? 'number' : 'text'}
                    disabled={disabled || busy}
                    min={field.min}
                    max={field.max}
                    step={field.step}
                    value={Array.isArray(selected) ? selected.join(', ') : String(selected)}
                    on:input={(event) => changeSetting(field, event.currentTarget.value)}
                  />
                {/if}
              </label>
            {/each}
          </div>
        </details>
      {/if}
    </section>
    <section class="writing-tool__pane writing-tool__pane--output">
      <div class="writing-tool__output">
        <slot name="output" {configuration} {renderMarkdown}><pre>{output}</pre></slot>
      </div>
      {#if corrections.length}
        <ul class="proofreader-tool__corrections" aria-label="Corrections">
          {#each corrections as correction, index (index)}
            <li>
              <del>{correction.original}</del> <ins>{correction.correction}</ins>
              {#if correction.types.length}<span> {correction.types.join(', ')}</span>{/if}
              {#if correction.explanation}<p>{correction.explanation}</p>{/if}
            </li>
          {/each}
        </ul>
      {/if}
      {#if copyText}<button type="button" disabled={disabled || busy} on:click={copy}
          >{copied ? 'Copied' : 'Copy output'}</button
        >{/if}
    </section>
  </div>
  {#if error || localError || availabilityError}<p class="writing-tool__error" role="alert">
      {error || localError || availabilityError}
    </p>{/if}
  <footer class="writing-tool__footer">
    <span>{inputUsage ?? '—'} / {inputQuota ?? '—'} tokens</span>
    {#if busy}
      <span role="status">
        {progressState?.phase ?? processing}
        {#if downloadProgress > 0 && downloadProgress < 100}
          {Math.round(downloadProgress)}%{/if}
        {#if progressState?.totalChunks}
          {progressState.processedChunks ?? 0}/{progressState.totalChunks}{/if}
      </span>
      {#if onInterrupt}<button type="button" {disabled} on:click={interrupt}>Stop</button>{/if}
    {/if}
    <button type="submit" data-browser-ai-action="run" disabled={disabled || busy || !value.trim()}>
      {busy ? 'Working…' : availability === 'downloadable' ? `Download & ${action.toLowerCase()}` : action}
    </button>
  </footer>
</form>
